name: TempBanUI
main: SonsaYT\TempBanUI\Main
api: [3.0.0, 4.0.0]
version: 1.8
author: SonsaYT

commands:
 tban:
  description: "Open TempBanUI"
  permission: use.tban
  
 tcheck:
  description: "Check ban list"
  permission: use.tcheck
