name: TempBanUIS
main: SonsaYT\TempBanUI\Main
api: [3.0.0, 4.0.0]
version: 2.3
author: SonsaYT

commands:
 mban:
  description: "Open TempBanUI"
  permission: use.mban
  
 mcheck:
  description: "Check ban list"
  permission: use.mcheck
